### ISSUE TITLE
`cachix push tweag` fails in CI

### ISSUE THREAD

**Issue by curiousleo** [tweag/funflow#146]
The last two CircleCI builds of `master` have failed: https://circleci.com/gh/tweag/funflow/tree/master, see for example https://circleci.com/gh/tweag/funflow/349. They all fail in the build step "Building", defined here: 
https://github.com/tweag/funflow/blob/1688c17a23ffd57900860ba4e26fc1749dafdfe3/.circleci/config.yml#L19

The error is as follows:
```
[...]
Killed

NoInput "You need to specify store paths either as stdin or as a cli argument"
Exited with code 1
```

This error is thrown here:
```haskell
  hasStdin <- not <$> hIsTerminalDevice stdin
  inputStorePaths <-
    case (hasStdin, cliPaths) of
      (False, []) -> throwIO $ NoInput "You need to specify store paths either as stdin or as an command argument"
```

https://github.com/cachix/cachix/blob/master/cachix/src/Cachix/Client/Commands.hs#L159

This implies that `hIsTerminalDevice stdin` is `true` on CircleCI (see https://hackage.haskell.org/package/base-4.12.0.0/docs/System-IO.html#v:hIsTerminalDevice), but needs to be `false` for `cachix` to read the list of packages to push from `stdin`.

**Comment by curiousleo** [comment]
https://stackoverflow.com/q/46172440 suggests that this could have something to do with the command running inside Docker. I don't know if CircleCI uses Docker.

**Comment by curiousleo** [comment]
In the `capability` project (where the relevant build step succeeds), the invocation of `cachix push tweag` looks a little different:

```yaml
  name: Push Cachix
  command: |
    # Instantiate nix-shell and push closure to project cache
    nix-shell --pure --run :
    nix-store -qR --include-outputs $(nix-instantiate shell.nix) | cachix push tweag
```
https://github.com/tweag/capability/blob/master/.circleci/config.yml#L25
